[build]
  base = "ECommerceGTFE"
  publish = "dist/ECommerceGTFE/browser"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200